<a href="https://colab.research.google.com/github/MWilliamsDP/AlphabetSoupChallenge/blob/main/AlphabetSoup2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
from google.colab import files
uploaded = files.upload()

Saving charity_data.csv to charity_data (2).csv

In [ ]:
import io
charity = pd.read_csv(io.BytesIO(uploaded['charity_data.csv']))
charity.head()

        EIN                                      NAME  ... ASK_AMT IS_SUCCESSFUL
0  10520599              BLUE KNIGHTS MOTORCYCLE CLUB  ...    5000             1
1  10531628    AMERICAN CHESAPEAKE CLUB CHARITABLE TR  ...  108590             1
2  10547893        ST CLOUD PROFESSIONAL FIREFIGHTERS  ...    5000             0
3  10553066            SOUTHSIDE ATHLETIC ASSOCIATION  ...    6692             1
4  10556103  GENETIC RESEARCH INSTITUTE OF THE DESERT  ...  142590             1

[5 rows x 12 columns]

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
charity.drop(['EIN', 'NAME'], axis=1, inplace=True)

In [ ]:
# Determine the number of unique values in each column.
charity.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts for binning
typeCounts=charity['APPLICATION_TYPE'].value_counts()
typeCounts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace=typeCounts[typeCounts < 100].index.tolist()

# Replace in dataframe
for app in application_types_to_replace:
    charity['APPLICATION_TYPE'] = charity['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
charity['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
Other      120
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts for binning
classification= charity['CLASSIFICATION'].value_counts()
classification.head(100)

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C2561        1
C1283        1
C2500        1
C1248        1
C1900        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification1=classifcation[classifcation>1]
classification1.head(100)

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C2300       32
C7200       32
C1240       30
C8000       20
C7120       18
C1500       16
C6000       15
C1800       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C4100        6
C1720        6
C1600        5
C1257        5
C2710        3
C1260        3
C0           3
C1234        2
C3200        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = classification1[classification1 <1000].index.tolist()
# Replace in dataframe
for cls in classifications_to_replace:
    charity['CLASSIFICATION'] = charity['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
charity['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2235
C3000     1918
C2100     1883
C1732        1
C4500        1
C1820        1
C4200        1
C1245        1
C1728        1
C2170        1
C1370        1
C3700        1
C2500        1
C1248        1
C8210        1
C2561        1
C2150        1
C1580        1
C1283        1
C1570        1
C2190        1
C6100        1
C2600        1
C1236        1
C5200        1
C4120        1
C2570        1
C2380        1
C1900        1
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`


CatEncoded=pd.get_dummies(charity, columns=['APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE','ORGANIZATION', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS'])
CatEncoded.head()

   STATUS  ASK_AMT  ...  SPECIAL_CONSIDERATIONS_N  SPECIAL_CONSIDERATIONS_Y
0       1     5000  ...                         1                         0
1       1   108590  ...                         1                         0
2       1     5000  ...                         1                         0
3       1     6692  ...                         1                         0
4       1   142590  ...                         1                         0

[5 rows x 71 columns]

In [ ]:
# Split our preprocessed data into our features and target arrays
y=CatEncoded['IS_SUCCESSFUL'].values
X=CatEncoded.drop(['IS_SUCCESSFUL'],1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=48)
X_train

array([[     1,   5000,      0, ...,      0,      1,      0],
       [     1,   5000,      0, ...,      0,      1,      0],
       [     1, 230189,      0, ...,      0,      1,      0],
       ...,
       [     1,   5000,      0, ...,      0,      1,      0],
       [     1,   5000,      0, ...,      0,      1,      0],
       [     1,  17649,      0, ...,      0,      1,      0]])

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
inputFeatures=len(X_train[0])
hiddenLayer1=2
hiddenLayer2=7

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hiddenLayer1, input_dim=inputFeatures, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hiddenLayer2, activation ='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation ='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_9 (Dense)             (None, 2)                 142

 dense_10 (Dense)            (None, 7)                 21

 dense_11 (Dense)            (None, 1)                 8

=================================================================
Total params: 171
Trainable params: 171
Non-trainable params: 0
_________________________________________________________________

In [ ]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=99)

Epoch 1/99
804/804 [==============================] - 2s 2ms/step - loss: 0.6220 - accuracy: 0.6712
Epoch 2/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5781 - accuracy: 0.7183
Epoch 3/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5706 - accuracy: 0.7193
Epoch 4/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5665 - accuracy: 0.7221
Epoch 5/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5645 - accuracy: 0.7218
Epoch 6/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5639 - accuracy: 0.7224
Epoch 7/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5633 - accuracy: 0.7220
Epoch 8/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5631 - accuracy: 0.7227
Epoch 9/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5629 - accuracy: 0.7220
Epoch 10/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5626 - accuracy: 0.7229
Epoch 11/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5628 - accuracy: 0.7231
Epoch 12/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5624 - accuracy: 0.7230
Epoch 13/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5624 - accuracy: 0.7217
Epoch 14/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5623 - accuracy: 0.7228
Epoch 15/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5622 - accuracy: 0.7222
Epoch 16/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5621 - accuracy: 0.7231
Epoch 17/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5620 - accuracy: 0.7230
Epoch 18/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5620 - accuracy: 0.7231
Epoch 19/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5620 - accuracy: 0.7229
Epoch 20/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5618 - accuracy: 0.7230
Epoch 21/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5617 - accuracy: 0.7236
Epoch 22/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5616 - accuracy: 0.7241
Epoch 23/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5616 - accuracy: 0.7238
Epoch 24/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5613 - accuracy: 0.7244
Epoch 25/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5614 - accuracy: 0.7245
Epoch 26/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5613 - accuracy: 0.7245
Epoch 27/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5613 - accuracy: 0.7249
Epoch 28/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5612 - accuracy: 0.7246
Epoch 29/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5611 - accuracy: 0.7246
Epoch 30/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5610 - accuracy: 0.7250
Epoch 31/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5611 - accuracy: 0.7245
Epoch 32/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5611 - accuracy: 0.7247
Epoch 33/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5609 - accuracy: 0.7254
Epoch 34/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5610 - accuracy: 0.7245
Epoch 35/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5609 - accuracy: 0.7243
Epoch 36/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5611 - accuracy: 0.7249
Epoch 37/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5608 - accuracy: 0.7249
Epoch 38/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5609 - accuracy: 0.7249
Epoch 39/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5610 - accuracy: 0.7241
Epoch 40/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5608 - accuracy: 0.7251
Epoch 41/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5607 - accuracy: 0.7252
Epoch 42/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5608 - accuracy: 0.7247
Epoch 43/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5610 - accuracy: 0.7250
Epoch 44/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5608 - accuracy: 0.7256
Epoch 45/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5604 - accuracy: 0.7252
Epoch 46/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5606 - accuracy: 0.7250
Epoch 47/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5609 - accuracy: 0.7248
Epoch 48/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5608 - accuracy: 0.7248
Epoch 49/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5606 - accuracy: 0.7252
Epoch 50/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5608 - accuracy: 0.7249
Epoch 51/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5607 - accuracy: 0.7247
Epoch 52/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5609 - accuracy: 0.7251
Epoch 53/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5607 - accuracy: 0.7249
Epoch 54/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5606 - accuracy: 0.7251
Epoch 55/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5607 - accuracy: 0.7252
Epoch 56/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5607 - accuracy: 0.7252
Epoch 57/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5606 - accuracy: 0.7255
Epoch 58/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5608 - accuracy: 0.7249
Epoch 59/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5607 - accuracy: 0.7247
Epoch 60/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5607 - accuracy: 0.7251
Epoch 61/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5606 - accuracy: 0.7250
Epoch 62/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5604 - accuracy: 0.7248
Epoch 63/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5607 - accuracy: 0.7244
Epoch 64/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5605 - accuracy: 0.7250
Epoch 65/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5604 - accuracy: 0.7250
Epoch 66/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5604 - accuracy: 0.7249
Epoch 67/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5606 - accuracy: 0.7247
Epoch 68/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5603 - accuracy: 0.7248
Epoch 69/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5603 - accuracy: 0.7248
Epoch 70/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5602 - accuracy: 0.7252
Epoch 71/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5603 - accuracy: 0.7252
Epoch 72/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5603 - accuracy: 0.7251
Epoch 73/99
804/804 [==============================] - 1s 2ms/step - loss: 0.5602 - accuracy: 0.7251
Epoch 74/99
804/804 [==============================] - 2s 2ms/step - loss: 0.5603 - accuracy: 0.7248
Epoch 75/99
804/804 [==============================] - 2s 2ms/step - loss: 0.5602 - accuracy: 0.7249
Epoch 76/99
804/804 [==============================] - 2s 2ms/step - loss: 0.5602 - accuracy: 0.7252
Epoch 77/99
804/804 [==============================] - 2s 2ms/step - loss: 0.5602 - accuracy: 0.7255
Epoch 78/99
804/804 [==============================] - 2s 2ms/step - loss: 0.5602 - accuracy: 0.7250
Epoch 79/99
804/804 [==============================] - 2s 2ms/step - loss: 0.5601 - accuracy: 0.7248
Epoch 80/99
804/804 [==============================] - 2s 2ms/step - loss: 0.5599 - accuracy: 0.7244
Epoch 81/99
804/804 [==============================] - 2s 2ms/step - loss: 0.5600 - accuracy: 0.7247
Epoch 82/99
804/804 [==============================] - 2s 2ms/step - loss: 0.5601 - accuracy: 0.7251
Epoch 83/99
804/804 [==============================] - 2s 2ms/step - loss: 0.5602 - accuracy: 0.7249
Epoch 84/99
804/804 [==============================] - 2s 2ms/step - loss: 0.5600 - accuracy: 0.7248
Epoch 85/99
804/804 [==============================] - 2s 2ms/step - loss: 0.5603 - accuracy: 0.7248
Epoch 86/99
804/804 [==============================] - 2s 2ms/step - loss: 0.5601 - accuracy: 0.7244
Epoch 87/99
804/804 [==============================] - 2s 2ms/step - loss: 0.5602 - accuracy: 0.7252
Epoch 88/99
804/804 [==============================] - 2s 2ms/step - loss: 0.5601 - accuracy: 0.7253
Epoch 89/99
804/804 [==============================] - 2s 2ms/step - loss: 0.5600 - accuracy: 0.7245
Epoch 90/99
804/804 [==============================] - 2s 2ms/step - loss: 0.5600 - accuracy: 0.7247
Epoch 91/99
804/804 [==============================] - 2s 2ms/step - loss: 0.5602 - accuracy: 0.7255
Epoch 92/99
804/804 [==============================] - 2s 2ms/step - loss: 0.5600 - accuracy: 0.7247
Epoch 93/99
804/804 [==============================] - 2s 2ms/step - loss: 0.5600 - accuracy: 0.7246
Epoch 94/99
804/804 [==============================] - 2s 2ms/step - loss: 0.5600 - accuracy: 0.7252
Epoch 95/99
804/804 [==============================] - 2s 2ms/step - loss: 0.5601 - accuracy: 0.7253
Epoch 96/99
804/804 [==============================] - 2s 2ms/step - loss: 0.5601 - accuracy: 0.7252
Epoch 97/99
804/804 [==============================] - 2s 2ms/step - loss: 0.5601 - accuracy: 0.7250
Epoch 98/99
804/804 [==============================] - 2s 2ms/step - loss: 0.5599 - accuracy: 0.7250
Epoch 99/99
804/804 [==============================] - 2s 2ms/step - loss: 0.5600 - accuracy: 0.7250

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5686 - accuracy: 0.7264 - 456ms/epoch - 2ms/step
Loss: 0.5686147212982178, Accuracy: 0.7264139652252197

In [76]:
# Export our model to HDF5 file
nn.save('AlphaetSoupCharity2.h5')